/**
 * Smart Inventory Alert DTO
 * Generated by velocity-based analysis of stock levels.
 */

export type AlertType = 'RESTOCK_URGENT' | 'LIQUIDATION';

export interface SmartInventoryAlert {
    productId: string;
    productName: string;
    sku: string;
    alertType: AlertType;
    /** Current units in stock */
    currentStock: number;
    /** Days until stockout at current velocity (RESTOCK_URGENT only) */
    estimatedDaysLeft?: number;
    /** Days since last stock receipt (LIQUIDATION only) */
    stockAgeDays?: number;
    /** Units sold in last 30 days (LIQUIDATION only) */
    monthlySales?: number;
    /** Product margin percentage */
    marginPercentage: number;
    /** Pre-formatted action message for WhatsApp report */
    recommendedAction: string;
}
