apiVersion: v1
kind: Secret
metadata:
  name: cypher-app-secrets
  namespace: cypher
type: Opaque
stringData:
  DB_PASSWORD: "replace-me"
  JWT_SECRET: "replace-me"
  JWT_REFRESH_SECRET: "replace-me"
  JWT_SECRET_B2B: "replace-me"
  JWT_REFRESH_SECRET_B2B: "replace-me"
  REDIS_PASSWORD: "replace-me"
  RABBITMQ_PASSWORD: "replace-me"
  MEILI_MASTER_KEY: "replace-me"
