apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cypher-ingress
  namespace: cypher
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging-erp.local
      secretName: cypher-staging-tls
  rules:
    - host: staging-erp.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cypher-app
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cypher-frontend
                port:
                  number: 80
    - host: erp.ledux.ro
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cypher-app
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cypher-frontend
                port:
                  number: 80
    - host: b2b.ledux.ro
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cypher-app
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cypher-frontend
                port:
                  number: 80
