apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace-cypher-data.yaml
  - data-plane.yaml
  - app-service-alias.yaml
patches:
  - path: app-configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: uploads-pvc-patch.yaml
  - path: hpa-behavior-patch.yaml
images:
  - name: ghcr.io/your-org/cypher-erp-app
    newName: cypher-erp-app
    newTag: latest
  - name: ghcr.io/your-org/cypher-erp-frontend
    newName: cypher-erp-frontend
    newTag: latest
